[project]
name = "spectral-anomalies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "jax>=0.7.1",
    "matplotlib>=3.10.5",
    "mpl-drip>=1.0.5",
    "pandas>=2.3.2",
    "tqdm>=4.67.1",
]
